/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package event_management_system;

/**
 *
 * @author chamika
 */
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.Statement;
import java.util.Base64;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.RowFilter;
import javax.swing.UIManager;

import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class Admin_Management extends javax.swing.JInternalFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Admin_Management.class.getName());

    /**
     * Creates new form manage_Bookings
     */
    PreparedStatement pst;
    ResultSet rs;
    Connection con = DBConnect.connect();

    public Admin_Management() {
        JPopupMenu.setDefaultLightWeightPopupEnabled(false);
        try {
            // Dark theme එකට:
            com.formdev.flatlaf.FlatDarkLaf.setup();

            // එහෙමත් නැත්නම් Light theme එකට:
            // UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize FlatLaf");
        }
        initComponents();
        visible_btn();

        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        String staffid = genarateUserId();
        lblNextId.setText(staffid);
        lblNextItemID.setText(generateItemId());
        loadItemTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAddStaff = new javax.swing.JButton();
        btnMannage = new javax.swing.JButton();
        btnEventAdd = new javax.swing.JButton();
        btnInventory = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jpAddStaff = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNextId = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtRole = new javax.swing.JComboBox<>();
        txtPassword = new javax.swing.JLabel();
        txrPassword = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CheckPassword = new javax.swing.JCheckBox();
        btnCreate = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtPasswordConfirm = new javax.swing.JPasswordField();
        jpMannageStaff = new javax.swing.JPanel();
        jpEventAdd = new javax.swing.JPanel();
        jpItemAdd = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        lblNameId = new javax.swing.JLabel();
        lblNextItemID = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtItemPrice = new javax.swing.JTextField();
        txtItemType = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();
        btnItemAdd = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnItemCancel = new javax.swing.JButton();
        btnItemUpadate = new javax.swing.JButton();
        btnItemDelete = new javax.swing.JButton();

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(1060, 600));
        setMinimumSize(new java.awt.Dimension(1060, 600));
        setPreferredSize(new java.awt.Dimension(1060, 600));

        jPanel1.setBackground(new java.awt.Color(40, 42, 54));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 1, 1, 1));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 600));
        jPanel1.setLayout(new java.awt.GridLayout(10, 1, 0, 10));

        btnAddStaff.setBackground(new java.awt.Color(102, 153, 255));
        btnAddStaff.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddStaff.setForeground(new java.awt.Color(255, 255, 255));
        btnAddStaff.setText("ADD STAFF");
        btnAddStaff.setBorderPainted(false);
        btnAddStaff.addActionListener(this::btnAddStaffActionPerformed);
        jPanel1.add(btnAddStaff);

        btnMannage.setBackground(new java.awt.Color(102, 153, 255));
        btnMannage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMannage.setForeground(new java.awt.Color(255, 255, 255));
        btnMannage.setText("MANAGE STAFF");
        btnMannage.setBorderPainted(false);
        btnMannage.addActionListener(this::btnMannageActionPerformed);
        jPanel1.add(btnMannage);

        btnEventAdd.setBackground(new java.awt.Color(102, 153, 255));
        btnEventAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEventAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnEventAdd.setText("EVENT ADD");
        btnEventAdd.setBorderPainted(false);
        btnEventAdd.addActionListener(this::btnEventAddActionPerformed);
        jPanel1.add(btnEventAdd);

        btnInventory.setBackground(new java.awt.Color(102, 153, 255));
        btnInventory.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnInventory.setForeground(new java.awt.Color(255, 255, 255));
        btnInventory.setText("INVENTORY");
        btnInventory.setBorderPainted(false);
        btnInventory.addActionListener(this::btnInventoryActionPerformed);
        jPanel1.add(btnInventory);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setLayout(new java.awt.CardLayout());

        jpAddStaff.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(26, 26, 36));

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtName.addActionListener(this::txtNameActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NAME");

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ASSIGN STAFF ID : ");

        lblNextId.setBackground(new java.awt.Color(51, 51, 51));
        lblNextId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNextId.setForeground(new java.awt.Color(255, 255, 255));

        txtContact.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtContact.addActionListener(this::txtContactActionPerformed);
        txtContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContactKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CONTACT NO.");

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtEmail.addActionListener(this::txtEmailActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("EMAIL");

        txtAddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtAddress.addActionListener(this::txtAddressActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ADDRESS");

        txtNId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNId.addActionListener(this::txtNIdActionPerformed);
        txtNId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNIdKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("National Id");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ADD STAFF ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtContact, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEmail)
                                    .addComponent(txtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)))
                            .addComponent(txtNId, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(lblNextId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(210, 210, 210))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNextId, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(135, 135, 135))
        );

        jpAddStaff.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 600));

        jPanel4.setBackground(new java.awt.Color(26, 26, 36));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Account  security");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 6, -1, 42));

        jLabel9.setBackground(new java.awt.Color(51, 51, 51));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ROLE");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 126, 115, 42));

        txtRole.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Event Planner", "Ticketing Staff", "Technical", "Analytics", "Administrator" }));
        jPanel4.add(txtRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 126, 220, 42));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setText("PASSOWORD");
        jPanel4.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 130, 40));

        txrPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txrPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txrPasswordKeyPressed(evt);
            }
        });
        jPanel4.add(txrPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 240, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CONFIRM pw.");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 127, 40));

        jLabel12.setForeground(new java.awt.Color(255, 0, 51));
        jLabel12.setText("After checking this box, ");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, 30));

        jLabel13.setForeground(new java.awt.Color(255, 0, 51));
        jLabel13.setText("the user can change the password the first time they log in.");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 330, 30));

        CheckPassword.setForeground(new java.awt.Color(255, 255, 255));
        CheckPassword.setText("First Time Can Be Change Password User ");
        CheckPassword.addActionListener(this::CheckPasswordActionPerformed);
        jPanel4.add(CheckPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 290, -1));

        btnCreate.setBackground(new java.awt.Color(153, 255, 204));
        btnCreate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(51, 51, 51));
        btnCreate.setText("CREATE ACCOUNT");
        btnCreate.addActionListener(this::btnCreateActionPerformed);
        jPanel4.add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 220, 40));

        jLabel14.setForeground(new java.awt.Color(255, 0, 51));
        jLabel14.setText("The Staff ID has been assigned as the default password.");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 32));

        jLabel15.setForeground(new java.awt.Color(255, 0, 51));
        jLabel15.setText("The password field was left empty. ");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, 32));

        txtPasswordConfirm.addActionListener(this::txtPasswordConfirmActionPerformed);
        jPanel4.add(txtPasswordConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 240, 40));

        jpAddStaff.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 0, 440, 600));

        jPanel2.add(jpAddStaff, "card3");

        javax.swing.GroupLayout jpMannageStaffLayout = new javax.swing.GroupLayout(jpMannageStaff);
        jpMannageStaff.setLayout(jpMannageStaffLayout);
        jpMannageStaffLayout.setHorizontalGroup(
            jpMannageStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 853, Short.MAX_VALUE)
        );
        jpMannageStaffLayout.setVerticalGroup(
            jpMannageStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jPanel2.add(jpMannageStaff, "card2");

        javax.swing.GroupLayout jpEventAddLayout = new javax.swing.GroupLayout(jpEventAdd);
        jpEventAdd.setLayout(jpEventAddLayout);
        jpEventAddLayout.setHorizontalGroup(
            jpEventAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 853, Short.MAX_VALUE)
        );
        jpEventAddLayout.setVerticalGroup(
            jpEventAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jPanel2.add(jpEventAdd, "card2");

        jpItemAdd.setBackground(new java.awt.Color(26, 26, 36));
        jpItemAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Item ADD");
        jpItemAdd.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 220, 60));

        txtItemName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jpItemAdd.add(txtItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 175, 193, 37));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Item Name");
        jpItemAdd.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 175, 132, 37));

        lblNameId.setBackground(new java.awt.Color(255, 255, 204));
        lblNameId.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNameId.setForeground(new java.awt.Color(255, 255, 255));
        lblNameId.setText("Next Item ID");
        jpItemAdd.add(lblNameId, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 120, 200, 37));

        lblNextItemID.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNextItemID.setForeground(new java.awt.Color(255, 255, 255));
        jpItemAdd.add(lblNextItemID, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 120, 130, 37));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Item Type");
        jpItemAdd.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 230, 132, 37));

        txtItemPrice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jpItemAdd.add(txtItemPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 285, 193, 37));

        txtItemType.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtItemType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Music", "Media", "Decor", "Furniture", "Food", "Others" }));
        jpItemAdd.add(txtItemType, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 230, 193, 37));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Item Price");
        jpItemAdd.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 285, 132, 37));

        itemTable.setBackground(new java.awt.Color(0, 0, 0));
        itemTable.setForeground(new java.awt.Color(255, 255, 255));
        itemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item ID", "Item Name", "Item Type", "Item Price"
            }
        ));
        itemTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        itemTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(itemTable);

        jpItemAdd.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 84, 486, 510));

        btnItemAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnItemAdd.setText("ADD ITEM");
        btnItemAdd.addActionListener(this::btnItemAddActionPerformed);
        jpItemAdd.add(btnItemAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 150, 39));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search_1.png"))); // NOI18N
        jpItemAdd.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, 50));

        txtSearch.addActionListener(this::txtSearchActionPerformed);
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        jpItemAdd.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 250, 33));

        btnItemCancel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnItemCancel.setText("CANCEL");
        btnItemCancel.addActionListener(this::btnItemCancelActionPerformed);
        jpItemAdd.add(btnItemCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 110, 40));

        btnItemUpadate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnItemUpadate.setText("UPDATE");
        btnItemUpadate.addActionListener(this::btnItemUpadateActionPerformed);
        jpItemAdd.add(btnItemUpadate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 110, 40));

        btnItemDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnItemDelete.setText("DELETE");
        btnItemDelete.addActionListener(this::btnItemDeleteActionPerformed);
        jpItemAdd.add(btnItemDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 110, 40));

        jPanel2.add(jpItemAdd, "card2");

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStaffActionPerformed
        jpAddStaff.setVisible(true);
        jpMannageStaff.setVisible(false);
        jpEventAdd.setVisible(false);
        jpItemAdd.setVisible(false);

    }//GEN-LAST:event_btnAddStaffActionPerformed

    private void btnMannageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMannageActionPerformed
        jpMannageStaff.setVisible(true);
        jpAddStaff.setVisible(false);
        jpEventAdd.setVisible(false);
        jpItemAdd.setVisible(false);
    }//GEN-LAST:event_btnMannageActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtNIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNIdActionPerformed

    private void CheckPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckPasswordActionPerformed

    private void txtPasswordConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordConfirmActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // --- Collect field values ---

        String name = txtName.getText().trim();
        String email = txtEmail.getText().trim();
        String address = txtAddress.getText().trim();
        String role = txtRole.getSelectedItem().toString();

        if (role.equals("Administrator")) {
            role = "admin";
        }

        String password = txrPassword.getText().trim();
        String confirmPassword = new String(txtPasswordConfirm.getPassword()).trim();

        String contactStr = txtContact.getText().trim();
        String nIdStr = txtNId.getText().trim();

        // --- Basic empty-field validation ---
        if (name.isEmpty() || email.isEmpty() || address.isEmpty()
                || contactStr.isEmpty() || nIdStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all required fields.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String emailPattern = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";

        if (!email.isEmpty() && !email.matches(emailPattern)) {
            JOptionPane.showMessageDialog(this,
                    "Please enter a valid email address!\n(e.g., example@gmail.com)",
                    "Invalid Email",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        long contact;
        double nId;
        try {
            contact = Long.parseLong(contactStr);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "Contact number must contain digits only.",
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            nId = Double.parseDouble(nIdStr);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "National ID must contain digits only.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // --- Generate next Staff ID ---
        String staffId = genarateUserId();

        if (password.isEmpty()) {
            jLabel15.setVisible(true);
            jLabel14.setVisible(true);
            password = staffId;
        } else {
            jLabel15.setVisible(false);
            jLabel14.setVisible(false);

            if (!password.equals(confirmPassword)) {
                JOptionPane.showMessageDialog(this, "Password and Confirm Password do not match.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            } else {

            }
        }

        // --- Duplicate check (email OR national ID already exists) ---
        if (checkUsername(email, nId)) {
            JOptionPane.showMessageDialog(this, "A staff member with this Email or National ID already exists.", "Duplicate Record", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {

            String finalPassword = encryptMyPassword(password);

            String sql = "INSERT INTO staff (staff_id, staff_name, contact_number, staff_email, "
                    + "staff_address, Id, role, password,first_time_log) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
            pst = con.prepareStatement(sql);
            pst.setString(1, staffId);
            pst.setString(2, name);
            pst.setLong(3, contact);
            pst.setString(4, email);
            pst.setString(5, address);
            pst.setDouble(6, nId);
            pst.setString(7, role);
            pst.setString(8, finalPassword);

            if (CheckPassword.isSelected()) {
                pst.setString(9, "1");
            } else {
                pst.setString(9, "0");
            }

            int rows = pst.executeUpdate();

            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Staff account created successfully!\nStaff ID: " + staffId, "Success", JOptionPane.INFORMATION_MESSAGE);

                txtName.setText("");
                txtContact.setText("");
                txtEmail.setText("");
                txtAddress.setText("");
                txtNId.setText("");
                txtPassword.setText("");
                txtPasswordConfirm.setText("");
                jLabel15.setVisible(false);
                jLabel14.setVisible(false);

                // Refresh the displayed next ID
                String nextId = genarateUserId();
                lblNextId.setText(nextId);

            } else {
                JOptionPane.showMessageDialog(this, "Failed to create staff account. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (java.sql.SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Admin_Management.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void txtContactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactKeyPressed
        txtContact.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!((c >= '0') && (c <= '9')
                        || (c == KeyEvent.VK_BACK_SPACE)
                        || (c == KeyEvent.VK_DELETE))) {
                    e.consume();
                }
            }
        });
    }//GEN-LAST:event_txtContactKeyPressed

    private void txtNIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNIdKeyPressed
        txtNId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent e) {
                char c = e.getKeyChar();

                //  (0-9), 'V', 'v',
                if (!((c >= '0') && (c <= '9')
                        || (c == 'V')
                        || (c == 'v')
                        || (c == java.awt.event.KeyEvent.VK_BACK_SPACE)
                        || (c == java.awt.event.KeyEvent.VK_DELETE))) {

                    e.consume();
                }
            }
        });
    }//GEN-LAST:event_txtNIdKeyPressed

    private void txrPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txrPasswordKeyPressed


    }//GEN-LAST:event_txrPasswordKeyPressed

    private void btnEventAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventAddActionPerformed
        jpEventAdd.setVisible(true);
        jpAddStaff.setVisible(false);
        jpMannageStaff.setVisible(false);
        jpItemAdd.setVisible(false);
    }//GEN-LAST:event_btnEventAddActionPerformed

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryActionPerformed
        jpItemAdd.setVisible(true);
        jpEventAdd.setVisible(false);
        jpAddStaff.setVisible(false);
        jpMannageStaff.setVisible(false);
    }//GEN-LAST:event_btnInventoryActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        try {
            loadItemTable();

            String searchString = txtSearch.getText();

            DefaultTableModel model = (DefaultTableModel) itemTable.getModel();

            TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(model);
            itemTable.setRowSorter(tr);

            tr.setRowFilter(RowFilter.regexFilter("(?i)" + searchString));

        } catch (Exception e) {
            System.out.println("Search Error: " + e.getMessage());
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnItemAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemAddActionPerformed
        try {
            String itemId, itemName, itemType, itemPrice;
            itemId = generateItemId();
            itemName = txtItemName.getText();
            itemType = txtItemType.getSelectedItem().toString();
            itemPrice = txtItemPrice.getText();
            if (itemId.isEmpty() || itemName.isEmpty() || itemType.isEmpty() || itemPrice.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Please Empty Fill Not Reqrerd");
                return;
            }
            String sql = "INSERT INTO resources( resource_id, resource_name, resource_type,cost_per_item ) VALUES(?,?,?,?)";
            pst = con.prepareStatement(sql);

            pst.setString(1, itemId);
            pst.setString(2, itemName);
            pst.setString(3, itemType);
            pst.setString(4, itemPrice);

            pst.executeUpdate();

            loadItemTable();
            lblNextItemID.setText(generateItemId());
            txtItemName.setText("");
            txtItemPrice.setText("");

        } catch (SQLException ex) {
            System.getLogger(Admin_Management.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

    }//GEN-LAST:event_btnItemAddActionPerformed

    private void btnItemCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemCancelActionPerformed
        visible_btn();
        lblNameId.setText("Next Item ID");
        lblNextItemID.setText(generateItemId());
        btnItemAdd.setVisible(true);
        txtItemName.setText("");
        txtItemType.setSelectedItem("");
        txtItemPrice.setText("");
        lblNameId.setForeground(new Color(242, 242, 242));
        lblNextItemID.setForeground(new Color(242, 242, 242));
    }//GEN-LAST:event_btnItemCancelActionPerformed

    private void btnItemUpadateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemUpadateActionPerformed
        try {
            String itemId, itemName, itemType, itemPrice;
            itemId = lblNextItemID.getText();
            itemName = txtItemName.getText();
            itemType = txtItemType.getSelectedItem().toString();
            itemPrice = txtItemPrice.getText();
            if (itemId.isEmpty() || itemName.isEmpty() || itemType.isEmpty() || itemPrice.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Please Empty Fill Not Reqrerd");
                return;
            }
            String sql = "UPDATE resources SET resource_name=?, resource_type=?, cost_per_item=? WHERE resource_id=?";
            pst = con.prepareStatement(sql);
            pst.setString(1, itemName);
            pst.setString(2, itemType);
            pst.setString(3, itemPrice);
            pst.setString(4, itemId);
            
            pst.executeUpdate();
            loadItemTable();
            txtItemName.setText("");
            txtItemPrice.setText("");
            btnItemCancel.doClick();
        } catch (SQLException ex) {
            System.getLogger(Admin_Management.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnItemUpadateActionPerformed

    private void btnItemDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemDeleteActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "Do you want to delete", "Delete", JOptionPane.YES_NO_OPTION);
        if (ok == JOptionPane.YES_OPTION) {
            try {
                
                String itemId=lblNextItemID.getText();
                // Database Update
                String sql = "DELETE FROM resources WHERE resource_id=? ";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, itemId);
                
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Client Delete Successfully!");
                
                loadItemTable();
                
                btnItemCancel.doClick();
                
            } catch (SQLException ex) {
                System.getLogger(client_Details.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
            
        }
    }//GEN-LAST:event_btnItemDeleteActionPerformed

    private void itemTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemTableMouseClicked
        int rowIndex = itemTable.getSelectedRow();

        DefaultTableModel iModel = (DefaultTableModel) itemTable.getModel();

        String item_id = iModel.getValueAt(rowIndex, 0).toString();
        String item_name = iModel.getValueAt(rowIndex, 1).toString();
        String item_type = iModel.getValueAt(rowIndex, 2).toString();
        String item_price = iModel.getValueAt(rowIndex, 3).toString();

        lblNameId.setText("Update Item Id");
        lblNameId.setForeground(Color.YELLOW);

        lblNextItemID.setText(item_id);
        lblNextItemID.setForeground(Color.red);

        txtItemName.setText(item_name);
        txtItemType.setSelectedItem(item_type);
        txtItemPrice.setText(item_price);
        btnItemAdd.setVisible(false);
        btnItemUpadate.setVisible(true);
        btnItemDelete.setVisible(true);
        btnItemCancel.setVisible(true);

    }//GEN-LAST:event_itemTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Admin_Management().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckPassword;
    private javax.swing.JButton btnAddStaff;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnEventAdd;
    private javax.swing.JButton btnInventory;
    private javax.swing.JButton btnItemAdd;
    private javax.swing.JButton btnItemCancel;
    private javax.swing.JButton btnItemDelete;
    private javax.swing.JButton btnItemUpadate;
    private javax.swing.JButton btnMannage;
    private javax.swing.JTable itemTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpAddStaff;
    private javax.swing.JPanel jpEventAdd;
    private javax.swing.JPanel jpItemAdd;
    private javax.swing.JPanel jpMannageStaff;
    private javax.swing.JLabel lblNameId;
    private javax.swing.JLabel lblNextId;
    private javax.swing.JLabel lblNextItemID;
    private javax.swing.JTextField txrPassword;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtItemPrice;
    private javax.swing.JComboBox<String> txtItemType;
    private javax.swing.JTextField txtNId;
    private javax.swing.JTextField txtName;
    private javax.swing.JLabel txtPassword;
    private javax.swing.JPasswordField txtPasswordConfirm;
    private javax.swing.JComboBox<String> txtRole;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private String genarateUserId() {
        String newId = "S-0001";  // default ID
        try {
            // MAX()
            String sql = "SELECT MAX(staff_id) AS max_id FROM staff";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            // Data  null 
            if (rs.next() && rs.getString("max_id") != null) {
                String lastId = rs.getString("max_id"); //ex : "S-0001"

                // "S-" (substring(2)
                int num = Integer.parseInt(lastId.substring(2));

                num++; // (1 -> 2)

                //"S-" 
                newId = String.format("S-%04d", num); //  "S-0002"
            }
        } catch (SQLException ex) {
            Logger.getLogger(Admin_Management.class.getName()).log(Level.SEVERE, null, ex);
        }
        return newId;
    }

    private boolean checkUsername(String email, double id) {
        try {
            String msg = "select * from staff where staff_email=? OR Id=?";
            pst = con.prepareStatement(msg);
            pst.setString(1, email);
            pst.setDouble(2, id);
            rs = pst.executeQuery();
            return rs.next();
        } catch (SQLException ex) {
            Logger.getLogger(Admin_Management.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;

    }

    private String encryptMyPassword(String password) {

        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256"); // Secure hashing
            byte[] hashBytes = md.digest(password.getBytes());
            return Base64.getEncoder().encodeToString(hashBytes);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(Admin_Management.class.getName()).log(Level.SEVERE, null, ex);
        }
        return "";

    }

    private String generateItemId() {
        String newId = "R-001";  // default ID
        try {
            // MAX()
            String sql = "SELECT MAX(resource_id) AS max_id FROM resources";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            // Data  null 
            if (rs.next() && rs.getString("max_id") != null) {
                String lastId = rs.getString("max_id"); //ex : "R-001"

                // "R-" (substring(2))
                int num = Integer.parseInt(lastId.substring(2));

                num++; // (1 -> 2)

                //"R-" 
                newId = String.format("R-%03d", num); //  "R-002"
            }
        } catch (SQLException ex) {
            // මෙතන 'manage_Resources' කියන එක ඔයාගේ Form එකේ නමට වෙනස් කරගන්න
            Logger.getLogger(Admin_Management.class.getName()).log(Level.SEVERE, null, ex);
        }
        return newId;
    }

    private void loadItemTable() {
        try {

            Statement s = con.createStatement();

            ResultSet rs = pst.executeQuery("SELECT * FROM resources");

            DefaultTableModel model = (DefaultTableModel) itemTable.getModel();
            model.setRowCount(0);

            while (rs.next()) {

                String item_id = rs.getString("resource_id");
                String item_name = rs.getString("resource_name");
                String item_type = rs.getString("resource_type");
                String item_price = rs.getString("cost_per_item");

                model.addRow(new Object[]{item_id, item_name, item_type, item_price});
            }
        } catch (SQLException ex) {
            System.getLogger(client_Details.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

    }

    private void visible_btn() {
        btnItemUpadate.setVisible(false);
        btnItemDelete.setVisible(false);
        btnItemCancel.setVisible(false);
    }

}
