/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package event_management_system;

/**
 *
 * @author chamika
 */
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.UIManager;
import javax.swing.table.TableRowSorter;

public class client_Details extends javax.swing.JInternalFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(client_Details.class.getName());

    /**
     * Creates new form manage_Bookings
     */
    String selectedClientID = "";
    Connection conn = DBConnect.connect();

    public client_Details() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        loadClientTable();
        btnUpdateClient.setVisible(false);
        btnCancelClient.setVisible(false);
        btnDelClient.setVisible(false);
        
        

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        btnCancelClient = new javax.swing.JButton();
        btnUpdateClient = new javax.swing.JButton();
        btnDelClient = new javax.swing.JButton();
        btnAddClient = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClients = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(1060, 600));
        setMinimumSize(new java.awt.Dimension(1060, 600));
        setPreferredSize(new java.awt.Dimension(1060, 600));

        jPanel1.setMaximumSize(new java.awt.Dimension(1060, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(1060, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(1060, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(24, 24, 38));
        jPanel2.setPreferredSize(new java.awt.Dimension(370, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Client ADD");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 148, 34));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID CARD NO");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 46, 120, 30));

        txtIdNo.setBackground(new java.awt.Color(51, 51, 51));
        txtIdNo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtIdNo.setForeground(new java.awt.Color(255, 255, 255));
        txtIdNo.setBorder(null);
        txtIdNo.setCaretColor(new java.awt.Color(255, 255, 255));
        txtIdNo.addActionListener(this::txtIdNoActionPerformed);
        txtIdNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdNoKeyPressed(evt);
            }
        });
        jPanel2.add(txtIdNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 82, 300, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NAME");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 130, 120, 30));

        txtName.setBackground(new java.awt.Color(51, 51, 51));
        txtName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setBorder(null);
        txtName.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 166, 300, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PHONE");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 214, 120, 30));

        txtPhone.setBackground(new java.awt.Color(51, 51, 51));
        txtPhone.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(255, 255, 255));
        txtPhone.setBorder(null);
        txtPhone.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPhoneKeyPressed(evt);
            }
        });
        jPanel2.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 250, 300, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("EMAIL");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 298, 120, 30));

        txtEmail.setBackground(new java.awt.Color(51, 51, 51));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(null);
        txtEmail.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 334, 300, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ADDRESS");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 382, 120, 30));

        txtAddress.setBackground(new java.awt.Color(51, 51, 51));
        txtAddress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(255, 255, 255));
        txtAddress.setBorder(null);
        txtAddress.setCaretColor(new java.awt.Color(255, 255, 255));
        txtAddress.setMaximumSize(new java.awt.Dimension(64, 22));
        jPanel2.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 418, 300, 88));

        btnCancelClient.setBackground(new java.awt.Color(51, 51, 51));
        btnCancelClient.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelClient.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelClient.setText("CANCEL");
        btnCancelClient.addActionListener(this::btnCancelClientActionPerformed);
        jPanel2.add(btnCancelClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 110, 50));

        btnUpdateClient.setBackground(new java.awt.Color(0, 102, 179));
        btnUpdateClient.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUpdateClient.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateClient.setText("UPDATE");
        btnUpdateClient.addActionListener(this::btnUpdateClientActionPerformed);
        jPanel2.add(btnUpdateClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 110, 50));

        btnDelClient.setBackground(new java.awt.Color(204, 0, 51));
        btnDelClient.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDelClient.setForeground(new java.awt.Color(255, 255, 255));
        btnDelClient.setText("DElETE");
        btnDelClient.addActionListener(this::btnDelClientActionPerformed);
        jPanel2.add(btnDelClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, 110, 50));

        btnAddClient.setBackground(new java.awt.Color(90, 120, 240));
        btnAddClient.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAddClient.setForeground(new java.awt.Color(255, 255, 255));
        btnAddClient.setText("ADD Client");
        btnAddClient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnAddClient.addActionListener(this::btnAddClientActionPerformed);
        jPanel2.add(btnAddClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 525, 300, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 600));

        jPanel3.setBackground(new java.awt.Color(24, 24, 38));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableClients.setBackground(new java.awt.Color(51, 51, 51));
        jTableClients.setForeground(new java.awt.Color(255, 255, 255));
        jTableClients.setGridColor(new java.awt.Color(102, 102, 102));
        jTableClients.setRowHeight(30);
        jTableClients.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTableClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Client_id", "name", "ID Card No", "Phone", "Email", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableClients.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jTableClients.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTableClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableClients);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 104, 678, 470));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Client Search");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 164, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search_1.png"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        txtSearch.setBorder(null);
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        jPanel3.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 421, 33));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 690, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdNoActionPerformed

    }//GEN-LAST:event_txtIdNoActionPerformed

    private void btnAddClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddClientActionPerformed
        try {

            String nic = txtIdNo.getText();
            String name = txtName.getText();
            String phone = txtPhone.getText();
            String email = txtEmail.getText();
            String address = txtAddress.getText();

            if (name.isEmpty() || phone.isEmpty() || nic.isEmpty() || address.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill the required fields!");
                return;
            }

            

            String checkSql = "SELECT * FROM clients WHERE nic = ?";
            PreparedStatement checkPst = conn.prepareStatement(checkSql);
            checkPst.setString(1, nic);
            ResultSet checkRs = checkPst.executeQuery();

            if (checkRs.next()) {

                JOptionPane.showMessageDialog(this, "This ID Card No (NIC) already exists in the system!", "Duplicate Record", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String newClientID = "C-1001";
            Statement s = conn.createStatement();
            ResultSet rs = s.executeQuery("SELECT MAX(client_id) FROM clients");

            if (rs.next() && rs.getString(1) != null) {
                String maxId = rs.getString(1); // C-1005
                long idNum = Long.parseLong(maxId.substring(2)); // C- 1005 
                idNum++; // (1006)
                newClientID = "C-" + String.format("%04d", idNum); //  C-1006
            }

            String sql = "INSERT INTO clients (client_id, client_name, nic, contact_number, email, address) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, newClientID);
            pst.setString(2, name);
            pst.setString(3, nic);
            pst.setString(4, phone);
            pst.setString(5, email);
            pst.setString(6, address);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Client Added Successfully!\nNew Client ID: " + newClientID);

            txtIdNo.setText("");
            txtName.setText("");
            txtPhone.setText("");
            txtEmail.setText("");
            txtAddress.setText("");

            loadClientTable();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }


    }//GEN-LAST:event_btnAddClientActionPerformed

    private void txtIdNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdNoKeyPressed
        txtIdNo.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!((c >= '0') && (c <= '9')
                        || (c == KeyEvent.VK_BACK_SPACE)
                        || (c == KeyEvent.VK_DELETE))) {
                    e.consume();
                }
            }
        });
    }//GEN-LAST:event_txtIdNoKeyPressed

    private void txtPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyPressed
        txtPhone.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!((c >= '0') && (c <= '9')
                        || (c == KeyEvent.VK_BACK_SPACE)
                        || (c == KeyEvent.VK_DELETE))) {
                    e.consume();
                }
            }
        });
    }//GEN-LAST:event_txtPhoneKeyPressed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        try {

            String searchString = txtSearch.getText();

            DefaultTableModel model = (DefaultTableModel) jTableClients.getModel();

            TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(model);
            jTableClients.setRowSorter(tr);

            tr.setRowFilter(RowFilter.regexFilter("(?i)" + searchString));

        } catch (Exception e) {
            System.out.println("Search Error: " + e.getMessage());
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void jTableClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientsMouseClicked
        try {

            int rowIndex = jTableClients.getSelectedRow();

            DefaultTableModel model = (DefaultTableModel) jTableClients.getModel();

            String id = model.getValueAt(rowIndex, 0).toString();
            String name = model.getValueAt(rowIndex, 1).toString();
            String nic = model.getValueAt(rowIndex, 2).toString();
            String phone = model.getValueAt(rowIndex, 3).toString();
            String email = model.getValueAt(rowIndex, 4).toString();
            String address = model.getValueAt(rowIndex, 5).toString();

            selectedClientID = id;

            txtName.setText(name);
            txtIdNo.setText(nic);
            txtPhone.setText(phone);
            txtEmail.setText(email);
            txtAddress.setText(address);

            btnAddClient.setVisible(false);
            btnUpdateClient.setVisible(true);
            btnCancelClient.setVisible(true);
            btnDelClient.setVisible(true);

        } catch (Exception e) {
            System.out.println("Table Click Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jTableClientsMouseClicked

    private void btnCancelClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelClientActionPerformed
        txtIdNo.setText("");
        txtName.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        txtAddress.setText("");

// 2. Select 
        selectedClientID = "";

// 3. Buttons 
        btnUpdateClient.setVisible(false);
        btnCancelClient.setVisible(false);
        btnAddClient.setVisible(true);
        btnDelClient.setVisible(false);
    }//GEN-LAST:event_btnCancelClientActionPerformed

    private void btnUpdateClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateClientActionPerformed
        try {
            String nic = txtIdNo.getText().trim();
            String name = txtName.getText().trim();
            String phone = txtPhone.getText().trim();
            String email = txtEmail.getText().trim();
            String address = txtAddress.getText().trim();

            if (selectedClientID.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please select a client from the table to update!");
                return;
            }

            if (name.isEmpty() || phone.isEmpty() || nic.isEmpty() || address.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill all the required fields!", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            

            // Database Update 
            String sql = "UPDATE clients SET client_name=?, nic=?, contact_number=?, email=?, address=? WHERE client_id=?";
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, name);
            pst.setString(2, nic);
            pst.setString(3, phone);
            pst.setString(4, email);
            pst.setString(5, address);
            pst.setString(6, selectedClientID);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Client Updated Successfully!");

            // Table
            loadClientTable();

            // Cancel Button Code Click 
            btnCancelClient.doClick();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateClientActionPerformed

    private void btnDelClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelClientActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "Do you want to delete", "Delete", JOptionPane.YES_NO_OPTION);
        if (ok == JOptionPane.YES_OPTION) {
            try {
                
                
                // Database Update
                String sql = "DELETE FROM clients WHERE client_id=? ";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, selectedClientID);
                
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Client Delete Successfully!");
                
                loadClientTable();
                
                btnCancelClient.doClick();
                
            } catch (SQLException ex) {
                System.getLogger(client_Details.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
            
        }
    }//GEN-LAST:event_btnDelClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            // Dark theme එකට:
            com.formdev.flatlaf.FlatDarkLaf.setup();

            // එහෙමත් නැත්නම් Light theme එකට:
            // UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize FlatLaf");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddClient;
    private javax.swing.JButton btnCancelClient;
    private javax.swing.JButton btnDelClient;
    private javax.swing.JButton btnUpdateClient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClients;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdNo;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void loadClientTable() {
        try {
            

            Statement s = conn.createStatement();

            ResultSet rs = s.executeQuery("SELECT * FROM clients");

            DefaultTableModel model = (DefaultTableModel) jTableClients.getModel();
            model.setRowCount(0);

            while (rs.next()) {

                String id = rs.getString("client_id");
                String name = rs.getString("client_name");
                String nic = rs.getString("nic");
                String phone = rs.getString("contact_number");
                String email = rs.getString("email");
                String address = rs.getString("address");

                model.addRow(new Object[]{id, name, nic, phone, email, address});
            }
        } catch (SQLException ex) {
            System.getLogger(client_Details.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

    }
}
