/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package event_management_system;

/**
 *
 * @author chamika
 */
public class customize_Resource extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(customize_Resource.class.getName());

    // Reference to the parent booking form (for data passing)
    private manage_Bookings parentForm;
    private String selectedPackageId;
    private javax.swing.JButton btnConfirm;

    /**
     * Parameterized constructor — called from manage_Bookings.
     * @param parentForm reference to the parent booking form
     * @param packageId  the currently selected package ID
     */
    public customize_Resource(manage_Bookings parentForm, String packageId) {
        initComponents();

        this.parentForm = parentForm;
        this.selectedPackageId = packageId;

        // ---- Replace the table model with 6 columns (Resource ID added) ----
        javax.swing.table.DefaultTableModel newModel = new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String[]{"Resource ID", "Item Name", "Quantity", "Unit Price", "Total Price", "Added From"}
        ) {
            Class[] types = new Class[]{
                String.class, String.class, Integer.class, Double.class, Double.class, String.class
            };
            boolean[] canEdit = new boolean[]{false, false, false, false, false, false};

            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        tblResources.setModel(newModel);

        // Optionally hide the Resource ID column from the user
        tblResources.getColumnModel().getColumn(0).setMinWidth(0);
        tblResources.getColumnModel().getColumn(0).setMaxWidth(0);
        tblResources.getColumnModel().getColumn(0).setWidth(0);

        // Load package dropdown from DB
        loadPackages();

        // Load all resources into cmbItems dropdown
        loadAllResources();

        // Set spinner minimum value to 1
        spnQty.setModel(new javax.swing.SpinnerNumberModel(1, 1, Integer.MAX_VALUE, 1));

        // Wire up Add Item button
        btnAddItem.addActionListener(this::btnAddItemActionPerformed);

        // Wire up Remove Item button
        btnRemoveItem.addActionListener(this::btnRemoveItemActionPerformed);

        // ---- Add Confirm button programmatically ----
        btnConfirm = new javax.swing.JButton();
        btnConfirm.setFont(new java.awt.Font("Segoe UI", 1, 18));
        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(this::btnConfirmActionPerformed);
        jPanel1.add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, 200, 42));

        // Auto-select the package if packageId was provided
        if (packageId != null && !packageId.isEmpty()) {
            for (int i = 0; i < cmbPackage.getItemCount(); i++) {
                if (cmbPackage.getItemAt(i).toString().startsWith(packageId)) {
                    cmbPackage.setSelectedIndex(i);
                    break;
                }
            }
        }

        // Initialize total to 0.00
        calculateTableTotal();
    }

    /**
     * No-arg constructor for standalone testing / NetBeans compatibility.
     */
    public customize_Resource() {
        this(null, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResources = new javax.swing.JTable();
        cmbPackage = new javax.swing.JComboBox<>();
        txtTotalAmount = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmbItems = new javax.swing.JComboBox<>();
        spnQty = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        btnAddItem = new javax.swing.JButton();
        btnRemoveItem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(26, 26, 36));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblResources.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item Name", "Quantity", "Unit Price", "Total Price", "Added From"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblResources);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 0, 510, 486));

        cmbPackage.setEditable(true);
        cmbPackage.addActionListener(this::cmbPackageActionPerformed);
        jPanel1.add(cmbPackage, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 25, 292, 42));
        jPanel1.add(txtTotalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 76, 292, 41));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Select package");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 25, 195, 42));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Total Price");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 73, 195, 41));

        jPanel2.setBackground(new java.awt.Color(0, 12, 28));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Select Item");

        cmbItems.setEditable(true);
        cmbItems.addActionListener(this::cmbItemsActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Quantity");

        btnAddItem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddItem.setText("Add");

        btnRemoveItem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRemoveItem.setText("Delete");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnQty)
                            .addComponent(cmbItems, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoveItem, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 144, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbItems, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnQty, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoveItem, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 135, 520, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPackageActionPerformed

        // ========================================================
        // LOAD PACKAGE LOGIC
        // When a package is selected, remove only previous package
        // rows (preserve Manual items), then append new package items.
        // ========================================================

        Object selectedItem = cmbPackage.getSelectedItem();
        if (selectedItem == null) {
            return;
        }

        String packageStr = selectedItem.toString().trim();
        if (packageStr.isEmpty() || packageStr.equals("Select Package")) {
            return;
        }

        try {
            // Extract the package_id from the format "PKG-001 - Package Name"
            String packageId = packageStr.split(" - ")[0].trim();
            this.selectedPackageId = packageId;

            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblResources.getModel();

            // Remove only package-sourced rows (preserve "Manual" rows)
            for (int i = model.getRowCount() - 1; i >= 0; i--) {
                Object addedFromVal = model.getValueAt(i, 5); // "Added From" column (index 5)
                if (addedFromVal != null && !"Manual".equals(addedFromVal.toString())) {
                    model.removeRow(i);
                }
            }

            // Fetch associated items via package_resources JOIN resources (including resource_id)
            try (java.sql.Connection con = DBConnect.connect();
                 java.sql.PreparedStatement pst = con.prepareStatement(
                     "SELECT r.resource_id, r.resource_name, pr.quantity, r.cost_per_item "
                     + "FROM package_resources pr "
                     + "JOIN resources r ON pr.resource_id = r.resource_id "
                     + "WHERE pr.package_id = ?")) {

                pst.setString(1, packageId);
                java.sql.ResultSet rs = pst.executeQuery();

                while (rs.next()) {
                    String resId = rs.getString("resource_id");
                    String itemName = rs.getString("resource_name");
                    int qty = rs.getInt("quantity");
                    double unitPrice = rs.getDouble("cost_per_item");
                    double itemTotal = qty * unitPrice;

                    // Skip if this resource already exists as a Manual item
                    boolean existsAsManual = false;
                    for (int i = 0; i < model.getRowCount(); i++) {
                        if (resId.equals(model.getValueAt(i, 0).toString())
                                && "Manual".equals(model.getValueAt(i, 5).toString())) {
                            existsAsManual = true;
                            break;
                        }
                    }

                    if (!existsAsManual) {
                        model.addRow(new Object[]{
                            resId,       // Resource ID (col 0)
                            itemName,    // Item Name (col 1)
                            qty,         // Quantity (col 2)
                            unitPrice,   // Unit Price (col 3)
                            itemTotal,   // Total Price (col 4)
                            packageId    // Added From (col 5)
                        });
                    }
                }
            }

            // Recalculate the grand total
            calculateTableTotal();

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error loading package items: " + e.getMessage(),
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_cmbPackageActionPerformed

    private void cmbItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbItemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbItemsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new customize_Resource().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnRemoveItem;
    private javax.swing.JComboBox<String> cmbItems;
    private javax.swing.JComboBox<String> cmbPackage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spnQty;
    private javax.swing.JTable tblResources;
    private javax.swing.JTextField txtTotalAmount;
    // End of variables declaration//GEN-END:variables

    // =====================================================================
    // 1. CALCULATE TABLE TOTAL
    //    Iterates through all rows in tblResources, sums the "Total Price"
    //    column (index 3), and displays the formatted grand total.
    // =====================================================================
    private void calculateTableTotal() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblResources.getModel();
        double grandTotal = 0.0;

        for (int i = 0; i < model.getRowCount(); i++) {
            Object value = model.getValueAt(i, 4); // "Total Price" column (index 4 in 6-col model)
            if (value != null) {
                grandTotal += Double.parseDouble(value.toString());
            }
        }

        // Display formatted to 2 decimal places
        txtTotalAmount.setText(String.format("%.2f", grandTotal));
    }

    // =====================================================================
    // 2. LOAD PACKAGES
    //    Fetches all packages from the database and populates cmbPackage.
    //    Format: "package_id - package_name"
    // =====================================================================
    private void loadPackages() {
        try {
            java.sql.Connection con = DBConnect.connect();
            String sql = "SELECT package_id, package_name FROM package ORDER BY package_id";
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery();

            cmbPackage.removeAllItems();
            cmbPackage.addItem("Select Package"); // Placeholder item

            while (rs.next()) {
                cmbPackage.addItem(rs.getString("package_id") + " - " + rs.getString("package_name"));
            }

            rs.close();
            pst.close();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error loading packages: " + e.getMessage(),
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    // =====================================================================
    // 3. LOAD ALL RESOURCES
    //    Fetches all items from the resources table and populates cmbItems.
    //    Format: "resource_id - resource_name"
    // =====================================================================
    private void loadAllResources() {
        try {
            java.sql.Connection con = DBConnect.connect();
            String sql = "SELECT resource_id, resource_name FROM resources ORDER BY resource_id";
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery();

            cmbItems.removeAllItems();
            cmbItems.addItem("Select Item"); // Placeholder item

            while (rs.next()) {
                cmbItems.addItem(rs.getString("resource_id") + " - " + rs.getString("resource_name"));
            }

            rs.close();
            pst.close();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error loading resources: " + e.getMessage(),
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    // =====================================================================
    // 4. ADD MANUAL ITEM (btnAddItem ActionPerformed)
    //    - Gets selected item from cmbItems and quantity from spnQty
    //    - Fetches cost_per_item from the database
    //    - If item already exists in the table, updates its qty & total
    //    - If not, adds a new row with "Added From" = "Manual"
    //    - Recalculates the grand total
    // =====================================================================
    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {

        // Validate that an item is selected
        Object selectedItem = cmbItems.getSelectedItem();
        if (selectedItem == null || selectedItem.toString().equals("Select Item")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please select an item from the dropdown.",
                    "Validation", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String itemStr = selectedItem.toString().trim();

        // Extract resource_id and resource_name from "resource_id - resource_name"
        String resourceId = itemStr.split(" - ")[0].trim();
        String resourceName = itemStr.substring(itemStr.indexOf(" - ") + 3).trim();

        // Get quantity from spinner
        int quantity = (int) spnQty.getValue();

        try (java.sql.Connection con = DBConnect.connect();
             java.sql.PreparedStatement pst = con.prepareStatement(
                 "SELECT cost_per_item FROM resources WHERE resource_id = ?")) {

            pst.setString(1, resourceId);
            java.sql.ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                double unitPrice = rs.getDouble("cost_per_item");
                double totalPrice = quantity * unitPrice;

                javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblResources.getModel();

                // Check if the item already exists by resource_id (column 0)
                boolean itemExists = false;
                for (int i = 0; i < model.getRowCount(); i++) {
                    String existingId = model.getValueAt(i, 0).toString();

                    if (existingId.equals(resourceId)) {
                        // Item exists — update quantity and total price
                        int existingQty = Integer.parseInt(model.getValueAt(i, 2).toString());
                        int newQty = existingQty + quantity;
                        double newTotal = newQty * unitPrice;

                        model.setValueAt(newQty, i, 2);       // Update Quantity (col 2)
                        model.setValueAt(newTotal, i, 4);     // Update Total Price (col 4)
                        model.setValueAt("Manual", i, 5);     // Mark as Manual (col 5)

                        itemExists = true;
                        break;
                    }
                }

                // If item does not exist, add a new row
                if (!itemExists) {
                    model.addRow(new Object[]{
                        resourceId,      // Resource ID (col 0)
                        resourceName,    // Item Name (col 1)
                        quantity,        // Quantity (col 2)
                        unitPrice,       // Unit Price (col 3)
                        totalPrice,      // Total Price (col 4)
                        "Manual"         // Added From (col 5)
                    });
                }

                // Recalculate the grand total
                calculateTableTotal();

            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Resource not found in the database.",
                        "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error adding item: " + e.getMessage(),
                    "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    // =====================================================================
    // 5. REMOVE ITEM (btnRemoveItem ActionPerformed)
    //    Removes the currently selected row from tblResources and
    //    recalculates the grand total.
    // =====================================================================
    private void btnRemoveItemActionPerformed(java.awt.event.ActionEvent evt) {

        int selectedRow = tblResources.getSelectedRow();

        if (selectedRow == -1) {
            // No row selected — show warning
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please select a row to remove.",
                    "No Selection", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Confirm before removing
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Are you sure you want to remove the selected item?",
                "Confirm Removal", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblResources.getModel();
            model.removeRow(selectedRow);

            // Recalculate the grand total
            calculateTableTotal();
        }
    }

    // =====================================================================
    // CONFIRM BUTTON — passes customized data back to parentForm
    // =====================================================================
    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblResources.getModel();

        if (model.getRowCount() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No items in the table. Please add items before confirming.",
                    "Validation", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Extract all rows into a List<Object[]>
        java.util.List<Object[]> items = new java.util.ArrayList<>();
        for (int i = 0; i < model.getRowCount(); i++) {
            Object[] row = new Object[]{
                model.getValueAt(i, 0), // Resource ID
                model.getValueAt(i, 1), // Item Name
                model.getValueAt(i, 2), // Quantity
                model.getValueAt(i, 3), // Unit Price
                model.getValueAt(i, 4), // Total Price
                model.getValueAt(i, 5)  // Added From
            };
            items.add(row);
        }

        // Get the grand total from txtTotalAmount
        double grandTotal = 0.0;
        try {
            grandTotal = Double.parseDouble(txtTotalAmount.getText().trim());
        } catch (NumberFormatException e) {
            grandTotal = 0.0;
        }

        // Pass data back to the parent form
        if (parentForm != null) {
            parentForm.setCustomizedData(grandTotal, items);
        }

        // Close this window
        this.dispose();
    }
}
