package event_management_system;

import java.awt.Color;
import javax.swing.UIManager;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.sql.Connection;
import java.sql.PreparedStatement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author chamika
 */
public class Dashboard extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    Color defaultColor, clickColor;
    Connection conn = DBConnect.connect();
    private int lastLogId = -1;  // log_id of the current login session

    public Dashboard(Staff staff) {
        initComponents();
        defaultColor = new Color(51, 51, 51);
        clickColor = new Color(102, 153, 255);
        Log_Loging(staff);
        lblID.setText(staff.getStaff_id());

        if (staff.getRole().equals("admin")) {
            menu_Am.setVisible(true);
        } else {
            menu_Am.setVisible(false);
        }

        menu_Mb.setBackground(defaultColor);
        menu_Cd.setBackground(defaultColor);
        menu_Ar.setBackground(defaultColor);
        menu_Es.setBackground(defaultColor);
        menu_Bc.setBackground(defaultColor);
        menu_Am.setBackground(defaultColor);

        // Override EXIT_ON_CLOSE so we can write logout_time before exiting
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                recordLogout();
                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        menuName = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblID1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        menu_Mb = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        menu_Cd = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        menu_Ar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        menu_Es = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        menu_Bc = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        menu_Am = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jDesktopPanel = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        menuName.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        menuName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event Management logo.png"))); // NOI18N

        lblID.setForeground(new java.awt.Color(0, 0, 0));

        lblID1.setForeground(new java.awt.Color(0, 0, 0));
        lblID1.setText("Your Staff ID :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(menuName, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 788, Short.MAX_VALUE)
                .addComponent(lblID1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuName, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblID1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 120));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        menu_Mb.setBackground(new java.awt.Color(51, 51, 51));
        menu_Mb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_MbMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu_MbMousePressed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Booking.png"))); // NOI18N
        jLabel4.setText("Manage Bookings");

        javax.swing.GroupLayout menu_MbLayout = new javax.swing.GroupLayout(menu_Mb);
        menu_Mb.setLayout(menu_MbLayout);
        menu_MbLayout.setHorizontalGroup(
            menu_MbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_MbLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 44, Short.MAX_VALUE))
        );
        menu_MbLayout.setVerticalGroup(
            menu_MbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4)
        );

        menu_Cd.setBackground(new java.awt.Color(51, 51, 51));
        menu_Cd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_CdMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu_CdMousePressed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search Client.png"))); // NOI18N
        jLabel5.setText("Client Details");

        javax.swing.GroupLayout menu_CdLayout = new javax.swing.GroupLayout(menu_Cd);
        menu_Cd.setLayout(menu_CdLayout);
        menu_CdLayout.setHorizontalGroup(
            menu_CdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_CdLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        menu_CdLayout.setVerticalGroup(
            menu_CdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5)
        );

        menu_Ar.setBackground(new java.awt.Color(51, 51, 51));
        menu_Ar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_ArMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu_ArMousePressed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(153, 153, 153));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Human Resources.png"))); // NOI18N
        jLabel6.setText("Assign Resources");
        jLabel6.setMaximumSize(new java.awt.Dimension(141, 50));
        jLabel6.setMinimumSize(new java.awt.Dimension(141, 50));

        javax.swing.GroupLayout menu_ArLayout = new javax.swing.GroupLayout(menu_Ar);
        menu_Ar.setLayout(menu_ArLayout);
        menu_ArLayout.setHorizontalGroup(
            menu_ArLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_ArLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        menu_ArLayout.setVerticalGroup(
            menu_ArLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_ArLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menu_Es.setBackground(new java.awt.Color(51, 51, 51));
        menu_Es.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu_EsMousePressed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Schedule.png"))); // NOI18N
        jLabel7.setText("Event Schedule");
        jLabel7.setMaximumSize(new java.awt.Dimension(141, 50));
        jLabel7.setMinimumSize(new java.awt.Dimension(141, 50));

        javax.swing.GroupLayout menu_EsLayout = new javax.swing.GroupLayout(menu_Es);
        menu_Es.setLayout(menu_EsLayout);
        menu_EsLayout.setHorizontalGroup(
            menu_EsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_EsLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        menu_EsLayout.setVerticalGroup(
            menu_EsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_EsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menu_Bc.setBackground(new java.awt.Color(51, 51, 51));
        menu_Bc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu_BcMousePressed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(153, 153, 153));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Billing Machine.png"))); // NOI18N
        jLabel8.setText("Billing & Cost");
        jLabel8.setMaximumSize(new java.awt.Dimension(141, 50));
        jLabel8.setMinimumSize(new java.awt.Dimension(141, 50));

        javax.swing.GroupLayout menu_BcLayout = new javax.swing.GroupLayout(menu_Bc);
        menu_Bc.setLayout(menu_BcLayout);
        menu_BcLayout.setHorizontalGroup(
            menu_BcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_BcLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 48, Short.MAX_VALUE))
        );
        menu_BcLayout.setVerticalGroup(
            menu_BcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_BcLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menu_Am.setBackground(new java.awt.Color(51, 51, 51));
        menu_Am.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_AmMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu_AmMousePressed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(153, 153, 153));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin Settings Male.png"))); // NOI18N
        jLabel9.setText("ADMIN MANAGEMENT");
        jLabel9.setMaximumSize(new java.awt.Dimension(141, 50));
        jLabel9.setMinimumSize(new java.awt.Dimension(141, 50));

        javax.swing.GroupLayout menu_AmLayout = new javax.swing.GroupLayout(menu_Am);
        menu_Am.setLayout(menu_AmLayout);
        menu_AmLayout.setHorizontalGroup(
            menu_AmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_AmLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        menu_AmLayout.setVerticalGroup(
            menu_AmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_AmLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(menu_Am, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(menu_Es, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(menu_Mb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(menu_Cd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(menu_Ar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(menu_Bc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(menu_Mb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menu_Cd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menu_Ar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menu_Es, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menu_Bc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menu_Am, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 220, 600));

        javax.swing.GroupLayout jDesktopPanelLayout = new javax.swing.GroupLayout(jDesktopPanel);
        jDesktopPanel.setLayout(jDesktopPanelLayout);
        jDesktopPanelLayout.setHorizontalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
        );
        jDesktopPanelLayout.setVerticalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 1060, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgroud.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menu_AmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_AmMousePressed
        menu_Mb.setBackground(defaultColor);
        menu_Cd.setBackground(defaultColor);
        menu_Ar.setBackground(defaultColor);
        menu_Es.setBackground(defaultColor);
        menu_Bc.setBackground(defaultColor);
        menu_Am.setBackground(clickColor);
        menuName.setText("ADMIN MANAGEMENT");
    }//GEN-LAST:event_menu_AmMousePressed

    private void menu_AmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_AmMouseClicked
        Admin_Management admin_Management = new Admin_Management();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(admin_Management).setVisible(true);

    }//GEN-LAST:event_menu_AmMouseClicked

    private void menu_ArMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_ArMouseClicked
     assign_resources assign_resources = new assign_resources();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(assign_resources).setVisible(true); 
    }//GEN-LAST:event_menu_ArMouseClicked

    private void menu_MbMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_menu_MbMousePressed
        // TODO add your handling code here:
        menu_Mb.setBackground(clickColor);
        menu_Cd.setBackground(defaultColor);
        menu_Ar.setBackground(defaultColor);
        menu_Es.setBackground(defaultColor);
        menu_Bc.setBackground(defaultColor);
        menu_Am.setBackground(defaultColor);

        menuName.setText("Manage Bookings");
    }// GEN-LAST:event_menu_MbMousePressed

    private void menu_CdMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_menu_CdMousePressed
        // TODO add your handling code here:
        menu_Mb.setBackground(defaultColor);
        menu_Cd.setBackground(clickColor);
        menu_Ar.setBackground(defaultColor);
        menu_Es.setBackground(defaultColor);
        menu_Bc.setBackground(defaultColor);
        menu_Am.setBackground(defaultColor);

        menuName.setText("Client Details");
    }// GEN-LAST:event_menu_CdMousePressed

    private void menu_ArMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_menu_ArMousePressed
        // TODO add your handling code here:
        menu_Mb.setBackground(defaultColor);
        menu_Cd.setBackground(defaultColor);
        menu_Ar.setBackground(clickColor);
        menu_Es.setBackground(defaultColor);
        menu_Bc.setBackground(defaultColor);
        menu_Am.setBackground(defaultColor);

        menuName.setText("Assign Resources");
    }// GEN-LAST:event_menu_ArMousePressed

    private void menu_EsMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_menu_EsMousePressed
        // TODO add your handling code here:
        menu_Mb.setBackground(defaultColor);
        menu_Cd.setBackground(defaultColor);
        menu_Ar.setBackground(defaultColor);
        menu_Es.setBackground(clickColor);
        menu_Bc.setBackground(defaultColor);
        menu_Am.setBackground(defaultColor);

        menuName.setText("Event Schedule");
    }// GEN-LAST:event_menu_EsMousePressed

    private void menu_BcMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_menu_BcMousePressed
        // TODO add your handling code here:
        menu_Mb.setBackground(defaultColor);
        menu_Cd.setBackground(defaultColor);
        menu_Ar.setBackground(defaultColor);
        menu_Es.setBackground(defaultColor);
        menu_Bc.setBackground(clickColor);
        menu_Am.setBackground(defaultColor);

        menuName.setText("Billing & Cost");
    }// GEN-LAST:event_menu_BcMousePressed

    private void menu_MbMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_menu_MbMouseClicked
        // TODO add your handling code here:
        manage_Bookings manage_Bookings = new manage_Bookings();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(manage_Bookings).setVisible(true);

    }// GEN-LAST:event_menu_MbMouseClicked

    private void menu_CdMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_menu_CdMouseClicked
        // TODO add your handling code here:
        client_Details client_details = new client_Details();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(client_details).setVisible(true);
    }// GEN-LAST:event_menu_CdMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        try {
            // Dark theme එකට:
            UIManager.setLookAndFeel(new FlatLightLaf());

            // එහෙමත් නැත්නම් Light theme එකට:
            // UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize FlatLaf");
        }
        // </editor-fold>

        /* Create and display the form */
        System.out.println();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblID1;
    private javax.swing.JLabel menuName;
    private javax.swing.JPanel menu_Am;
    private javax.swing.JPanel menu_Ar;
    private javax.swing.JPanel menu_Bc;
    private javax.swing.JPanel menu_Cd;
    private javax.swing.JPanel menu_Es;
    private javax.swing.JPanel menu_Mb;
    // End of variables declaration//GEN-END:variables

    private void Log_Loging(Staff staff) {
        try {
            String logSql = "INSERT INTO staff_log (staff_id) VALUES (?)";
            PreparedStatement logPst = conn.prepareStatement(logSql,
                    java.sql.Statement.RETURN_GENERATED_KEYS);
            logPst.setString(1, staff.getStaff_id());
            logPst.executeUpdate();

            // Capture the auto-generated log_id for this session
            java.sql.ResultSet generatedKeys = logPst.getGeneratedKeys();
            if (generatedKeys.next()) {
                lastLogId = generatedKeys.getInt(1);
            }
        } catch (Exception ex) {
            System.out.println("Login Log Error: " + ex.getMessage());
        }
    }

    /**
     * Updates the logout_time in staff_log for the current session. Called
     * automatically when the Dashboard window is closed.
     */
    private void recordLogout() {
        if (lastLogId < 0) {
            return; // no valid session id
        }
        try {
            String sql = "UPDATE staff_log SET logout_time = NOW() WHERE log_id = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, lastLogId);
            pst.executeUpdate();
        } catch (Exception ex) {
            System.out.println("Logout Log Error: " + ex.getMessage());
        }
    }
}
