/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package event_management_system;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Image;
import java.awt.Taskbar;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Base64;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import java.util.Arrays;
import javax.swing.ImageIcon;

/**
 *
 * @author chamika
 */
public class Loging extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Loging.class.getName());

    /**
     * Creates new form
     */
    PreparedStatement pst;
    DBConnect db = new DBConnect();
    Connection conn = DBConnect.connect();
    ResultSet rs;

    public Loging() {
        initComponents();
        try {
            // Dark theme එකට:
            UIManager.setLookAndFeel(new FlatDarkLaf());

            // එහෙමත් නැත්නම් Light theme එකට:
            // UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize FlatLaf");
        }
        
        //logo create
        try {
           
            URL iconURL = getClass().getResource("/images/logo.png");
            Image taskbarIcon = new ImageIcon(iconURL).getImage();

           
            this.setIconImage(taskbarIcon);

           
            if (Taskbar.isTaskbarSupported()) {
                Taskbar taskbar = Taskbar.getTaskbar();

                if (taskbar.isSupported(Taskbar.Feature.ICON_IMAGE)) {
                    taskbar.setIconImage(taskbarIcon);
                }
            }
        } catch (Exception e) {
            System.out.println("Icon failed to load: " + e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnLoging = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsername.addActionListener(this::txtUsernameActionPerformed);
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 260, 40));

        txtPassword.addActionListener(this::txtPasswordActionPerformed);
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 260, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 90, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email or Staff_Id");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 120, 20));

        jLabel4.setFont(new java.awt.Font("Sitka Subheading", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Welcome Back !");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 280, 40));

        btnLoging.setBackground(new java.awt.Color(153, 153, 255));
        btnLoging.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnLoging.setForeground(new java.awt.Color(255, 255, 255));
        btnLoging.setText("Login");
        btnLoging.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogingMouseClicked(evt);
            }
        });
        btnLoging.addActionListener(this::btnLogingActionPerformed);
        jPanel1.add(btnLoging, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 220, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Event Management logo.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Blue Flat Color UI Login Page Desktop Prototype.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        keyPressed(evt);
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void btnLogingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogingMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogingMouseClicked

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtUsernameActionPerformed

    private void btnLogingActionPerformed(java.awt.event.ActionEvent evt) {
        String enteredUsername = txtUsername.getText().trim();
        char[] passwordChars = txtPassword.getPassword();
        String enteredPassword = new String(passwordChars).trim();
        Arrays.fill(passwordChars, ' '); // wipe char array

        // Delegate ALL authentication (including first-time reset) to performLogin
        performLogin(enteredUsername, enteredPassword);
    }

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Loging().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoging;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void keyPressed(KeyEvent e) {
        if (e.getKeyCode() == KeyEvent.VK_ENTER) {
            btnLoging.doClick();
        }
    }

    private void performLogin(String username, String password) {
        if (username == null || username.trim().isEmpty()
                || password == null || password.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please enter both username and password.",
                    "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (conn == null) {
            conn = DBConnect.connect();
        }
        if (conn == null) {
            JOptionPane.showMessageDialog(this,
                    "Cannot connect to the database!\nPlease check your MySQL server.",
                    "Database Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            String encryptedPassword = encryptMyPassword(password);
            System.out.println(encryptedPassword);
            String query
                    = "SELECT *, first_time_log FROM staff "
                    + "WHERE (staff_id = ? OR staff_email = ? OR Id = ?) AND password = ?";
            pst = conn.prepareStatement(query);
            pst.setString(1, username);
            pst.setString(2, username);
            pst.setString(3, username);
            pst.setString(4, encryptedPassword);
            rs = pst.executeQuery();

            if (!rs.next()) {
                JOptionPane.showMessageDialog(this,
                        "Incorrect username or password.\nPlease try again.",
                        "Login Failed", JOptionPane.ERROR_MESSAGE);
                txtPassword.setText("");
                txtPassword.requestFocus();
                return;
            }

            Staff staff = new Staff(
                    rs.getString(1), // staff_id
                    rs.getString(2), // staff_name
                    rs.getInt(3), // contact_number
                    rs.getString(4), // staff_email
                    rs.getString(5), // staff_address
                    rs.getString(6), // Id (NIC)
                    rs.getString(7) // role
            );
            int firstTimeLog = rs.getInt("first_time_log");

            UserSession.loggedUserRole = staff.getRole();
            UserSession.loggedUserName = staff.getStaff_name();

            if (firstTimeLog == 0) {

                First_time_log resetDialog = new First_time_log(this, staff);
                resetDialog.setVisible(true);

                if (!resetDialog.isPasswordChanged()) {

                    JOptionPane.showMessageDialog(this,
                            "Password change was cancelled.\nYou must set a new password on your first login.",
                            "Login Aborted", JOptionPane.WARNING_MESSAGE);
                    UserSession.clear();
                    return;
                }

            }

            JOptionPane.showMessageDialog(this,
                    "Welcome, " + staff.getStaff_name() + "!\nLogin successful.",
                    "Success", JOptionPane.INFORMATION_MESSAGE);
            new Dashboard(staff).setVisible(true);
            this.dispose();

        } catch (SQLException ex) {
            Logger.getLogger(Loging.class.getName()).log(Level.SEVERE, "Login query failed", ex);
            JOptionPane.showMessageDialog(this,
                    "A database error occurred:\n" + ex.getMessage(),
                    "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private String encryptMyPassword(String paasword) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256"); // Secure hashing
            byte[] hashBytes = md.digest(paasword.getBytes());
            return Base64.getEncoder().encodeToString(hashBytes);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(Loging.class.getName()).log(Level.SEVERE, null, ex);
        }
        return "";

    }
}
