/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package event_management_system;

/**
 *
 * @author chamika
 */
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPopupMenu;

public class manage_Bookings extends javax.swing.JInternalFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(manage_Bookings.class.getName());

    /**
     * Creates new form manage_Bookings
     */
    Connection con = DBConnect.connect();
    PreparedStatement pst;
    ResultSet rs;
    private boolean isUpdating = false;
    private java.util.List<Object[]> customizedItems = null;

    public manage_Bookings() {
        initComponents();

        JPopupMenu.setDefaultLightWeightPopupEnabled(false);

        NextBid.setText(BookingIdGenarate()); // initComponents() පසුව call කිරීම

        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);

        // cmbContact editor field ගෙන KeyListener එක add කිරීම
        javax.swing.JTextField txtContactSearch = (javax.swing.JTextField) cmbContact.getEditor().getEditorComponent();

        txtContactSearch.addKeyListener(new java.awt.event.KeyAdapter() {

            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                int keyCode = evt.getKeyCode();

                if (keyCode == java.awt.event.KeyEvent.VK_UP
                        || keyCode == java.awt.event.KeyEvent.VK_DOWN) {
                    isUpdating = true;
                }

                if (keyCode == java.awt.event.KeyEvent.VK_ENTER) {
                    if (cmbContact.isPopupVisible()) {
                        Object selected = cmbContact.getSelectedItem();
                        if (selected != null) {
                            String selectedStr = selected.toString().trim();
                            String contactNo = selectedStr.contains(" - ")
                                    ? selectedStr.split(" - ")[0].trim()
                                    : selectedStr;

                            isUpdating = true;
                            cmbContact.getEditor().setItem(contactNo);
                            cmbContact.hidePopup();
                            isUpdating = false;

                            fetchClientDetails(contactNo);
                        }
                        evt.consume();
                    }
                }
            }

            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                int keyCode = evt.getKeyCode();

                if (keyCode == java.awt.event.KeyEvent.VK_UP
                        || keyCode == java.awt.event.KeyEvent.VK_DOWN) {
                    isUpdating = false;
                    return;
                }

                if (keyCode == java.awt.event.KeyEvent.VK_ENTER
                        || keyCode == java.awt.event.KeyEvent.VK_LEFT
                        || keyCode == java.awt.event.KeyEvent.VK_RIGHT) {
                    return;
                }

                String text = txtContactSearch.getText().trim();
                if (text.length() >= 2) {
                    suggestContacts(text);
                } else {
                    cmbContact.hidePopup();
                }
            }
        });

        // Booking Save button
        jButton1.addActionListener(this::addBookingActionPerformed);

        // Package, time, payment status load කිරීම
        loadPackages();
        loadStartTimes();
        loadPaymentStatus();

        // Total / Advance change වූ විට Balance auto-calculate
        txtTotalAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                calculateBalance();
            }
        });
        txtAdvance.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                calculateBalance();
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtTotalAmount = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtAdvance = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        cmbPaymentStatus = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NextBid = new javax.swing.JLabel();
        cmbContact = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        cmbPackage = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtEventDate = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtStartTime = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtVenue = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtGuestCount = new javax.swing.JSpinner();
        btnCustomize = new javax.swing.JButton();

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(1060, 600));
        setMinimumSize(new java.awt.Dimension(1060, 600));
        setPreferredSize(new java.awt.Dimension(1060, 600));
        setVisible(true);

        jPanel1.setMaximumSize(new java.awt.Dimension(1060, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(1060, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(1060, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(26, 26, 36));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("TotalAmount");

        txtTotalAmount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Advance");

        txtAdvance.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Balance");

        txtBalance.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        cmbPaymentStatus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("PaymentStatus");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Booking Save");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtAdvance, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbPaymentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAdvance, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPaymentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 540, 610));

        jPanel3.setBackground(new java.awt.Color(26, 26, 36));
        jPanel3.setForeground(new java.awt.Color(26, 26, 36));
        jPanel3.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel1.setText("Manage Booking");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Booking_ID");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Client Contact Number");

        NextBid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        cmbContact.setEditable(true);
        cmbContact.setActionCommand("");
        cmbContact.addActionListener(this::cmbContactActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Client Name");

        txtName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        cmbPackage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Package Name");

        txtEventDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Event Date");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Start Time");

        txtStartTime.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Venue");

        txtVenue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Guest Count");

        txtGuestCount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        btnCustomize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Circled Right.png"))); // NOI18N
        btnCustomize.setText("custamize ");
        btnCustomize.addActionListener(this::btnCustomizeActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(99, 99, 99)
                        .addComponent(NextBid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbContact, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(cmbPackage, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCustomize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEventDate, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtVenue, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtGuestCount, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(67, 67, 67)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NextBid, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbContact, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbPackage, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCustomize, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEventDate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVenue, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGuestCount, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbContactActionPerformed

        if (isUpdating) {
            return;
        }

        Object item = cmbContact.getSelectedItem();

        if (item != null) {
            String selectedItem = item.toString().trim();
            if (selectedItem.isEmpty()) {
                return;
            }

            String contactNo = selectedItem;

            if (selectedItem.contains(" - ")) {
                contactNo = selectedItem.split(" - ")[0].trim(); // අංකය පමණක් වෙන් කිරීම

                final String finalContact = contactNo;

                javax.swing.SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                        isUpdating = true;
                        cmbContact.getEditor().setItem(finalContact);
                        cmbContact.hidePopup(); // ලිස්ට් එක හංගනවා
                        isUpdating = false;
                    }
                });
            }

            if ("comboBoxEdited".equals(evt.getActionCommand()) || "comboBoxChanged".equals(evt.getActionCommand())) {

                fetchClientDetails(contactNo);
            }
        }
    }//GEN-LAST:event_cmbContactActionPerformed

    private void btnCustomizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomizeActionPerformed
        // Validate that a package is selected before opening customization
        Object pkgItem = cmbPackage.getSelectedItem();
        if (pkgItem == null || pkgItem.toString().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a Package first.",
                    "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Extract package_id from "PKG-001 - Package Name"
        String pkgStr = pkgItem.toString();
        String selectedPkgId = pkgStr.contains(" - ") ? pkgStr.split(" - ")[0].trim() : pkgStr.trim();

        // Open customize_Resource with parent reference and package ID
        customize_Resource cr = new customize_Resource(this, selectedPkgId);
        cr.setVisible(true);
    }//GEN-LAST:event_btnCustomizeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize FlatLaf");
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NextBid;
    private javax.swing.JButton btnCustomize;
    private javax.swing.JComboBox<String> cmbContact;
    private javax.swing.JComboBox<String> cmbPackage;
    private javax.swing.JComboBox<String> cmbPaymentStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtAdvance;
    private javax.swing.JTextField txtBalance;
    private com.toedter.calendar.JDateChooser txtEventDate;
    private javax.swing.JSpinner txtGuestCount;
    private javax.swing.JTextField txtName;
    private javax.swing.JComboBox<String> txtStartTime;
    private javax.swing.JTextField txtTotalAmount;
    private javax.swing.JTextField txtVenue;
    // End of variables declaration//GEN-END:variables

    // =====================================================================
    // PUBLIC METHOD: Called by customize_Resource to pass customized data
    // =====================================================================
    public void setCustomizedData(double totalAmount, java.util.List<Object[]> items) {
        this.customizedItems = items;
        txtTotalAmount.setText(String.format("%.2f", totalAmount));
        calculateBalance();
    }

    private void suggestContacts(String text) {
        isUpdating = true;
        try (
                java.sql.Connection conn = DBConnect.connect(); java.sql.PreparedStatement stmt = conn.prepareStatement(
                "SELECT contact_number, client_name FROM clients WHERE contact_number LIKE ?"
        );) {
            stmt.setString(1, "%" + text + "%");
            java.sql.ResultSet result = stmt.executeQuery();

            cmbContact.removeAllItems();

            boolean hasData = false;
            while (result.next()) {
                hasData = true;
                cmbContact.addItem(result.getString("contact_number") + " - " + result.getString("client_name"));
            }

            // User type කළ text editor field එකේ restore කිරීම
            javax.swing.JTextField editor = (javax.swing.JTextField) cmbContact.getEditor().getEditorComponent();
            editor.setText(text);

            if (hasData) {
                cmbContact.showPopup();
            } else {
                cmbContact.hidePopup();
            }

        } catch (Exception e) {
            e.printStackTrace();
        } finally {

            isUpdating = false;
        }
    }

    private void fetchClientDetails(String contactNo) {
        try {

            String sql = "SELECT client_name FROM clients WHERE contact_number = ?";
            pst = con.prepareStatement(sql);
            pst.setString(1, contactNo);
            rs = pst.executeQuery();

            if (rs.next()) {

                txtName.setText(rs.getString("client_name"));
            } else {

                txtName.setText("");
                JOptionPane.showMessageDialog(this, "New Client! Please enter the Name.", "Info", JOptionPane.INFORMATION_MESSAGE);
                txtName.requestFocus();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // ===================== Booking Save =====================
    private void addBookingActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            // --- 1. Input Validation ---
            String eventId = NextBid.getText().trim();

            // Contact number (cmbContact editor ගෙන්)
            String contactNo = cmbContact.getEditor().getEditorComponent() instanceof javax.swing.JTextField
                    ? ((javax.swing.JTextField) cmbContact.getEditor().getEditorComponent()).getText().trim()
                    : "";

            if (contactNo.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter Client Contact Number.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                cmbContact.requestFocus();
                return;
            }

            String clientName = txtName.getText().trim();
            if (clientName.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Client Name is empty. Please select a valid contact.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Package
            Object pkgItem = cmbPackage.getSelectedItem();
            if (pkgItem == null || pkgItem.toString().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please select a Package.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                cmbPackage.requestFocus();
                return;
            }

            // Event Date
            java.util.Date selectedDate = txtEventDate.getDate();
            if (selectedDate == null) {
                JOptionPane.showMessageDialog(this, "Please select Event Date.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                txtEventDate.requestFocus();
                return;
            }

            // Start Time
            Object startTimeItem = txtStartTime.getSelectedItem();
            if (startTimeItem == null || startTimeItem.toString().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please select Start Time.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                txtStartTime.requestFocus();
                return;
            }

            String venue = txtVenue.getText().trim();
            if (venue.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter Venue.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                txtVenue.requestFocus();
                return;
            }

            int guestCount = (int) txtGuestCount.getValue();
            if (guestCount <= 0) {
                JOptionPane.showMessageDialog(this, "Guest Count must be greater than 0.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                txtGuestCount.requestFocus();
                return;
            }

            // Billing fields
            String totalStr = txtTotalAmount.getText().trim();
            String advanceStr = txtAdvance.getText().trim();
            if (totalStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter Total Amount.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                txtTotalAmount.requestFocus();
                return;
            }

            double totalAmount, advancePayment, balanceDue;
            try {
                totalAmount = Double.parseDouble(totalStr);
                advancePayment = advanceStr.isEmpty() ? 0.0 : Double.parseDouble(advanceStr);
                balanceDue = totalAmount - advancePayment;
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Total Amount and Advance must be valid numbers.", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Object payStatusItem = cmbPaymentStatus.getSelectedItem();
            String paymentStatus = (payStatusItem != null) ? payStatusItem.toString() : "Pending";

            // --- 2. Get client_id from contact number ---
            String clientId = getClientId(contactNo);
            if (clientId == null) {
                JOptionPane.showMessageDialog(this, "Client not found for contact: " + contactNo + "\nPlease register the client first.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // --- 3. Get package_id from selected package ---
            String pkgStr = pkgItem.toString(); // format: "P-1001 - Wedding Premium"
            String packageId = pkgStr.contains(" - ") ? pkgStr.split(" - ")[0].trim() : pkgStr.trim();

            // --- 4. Get staff_id from last login session ---
            String staffId = getLoggedInStaffId();

            // --- 5. Prepare date and time ---
            java.sql.Date eventDate = new java.sql.Date(selectedDate.getTime());
            String startTimeStr = startTimeItem.toString(); // format: "08:00 AM"
            java.sql.Time startTime = parseTime(startTimeStr);

            // --- 6. Insert into events table ---
            String sqlEvent = "INSERT INTO events (event_id, client_id, staff_id, package_id, event_date, start_time, venue, guest_count, event_status) "
                    + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'Upcoming')";
            pst = con.prepareStatement(sqlEvent);
            pst.setString(1, eventId);
            pst.setString(2, clientId);
            pst.setString(3, staffId);
            pst.setString(4, packageId);
            pst.setDate(5, eventDate);
            pst.setTime(6, startTime);
            pst.setString(7, venue);
            pst.setInt(8, guestCount);
            pst.executeUpdate();

            // --- 7. Insert into billing table ---
            String billId = generateBillId();
            String sqlBill = "INSERT INTO billing (bill_id, event_id, total_amount, advance_payment, balance_due, payment_status) "
                    + "VALUES (?, ?, ?, ?, ?, ?)";
            pst = con.prepareStatement(sqlBill);
            pst.setString(1, billId);
            pst.setString(2, eventId);
            pst.setDouble(3, totalAmount);
            pst.setDouble(4, advancePayment);
            pst.setDouble(5, balanceDue);
            pst.setString(6, paymentStatus);
            pst.executeUpdate();

            // --- 8. Save event resources to event_resources table ---
            int nextAssignNum = 1;
            pst = con.prepareStatement("SELECT MAX(assignment_id) AS max_id FROM event_resources");
            rs = pst.executeQuery();
            if (rs.next() && rs.getString("max_id") != null) {
                String lastId = rs.getString("max_id");
                nextAssignNum = Integer.parseInt(lastId.substring(4)) + 1;
            }

            String sqlRes = "INSERT INTO event_resources (assignment_id, event_id, resource_id, quantity, total_cost, package_id) "
                    + "VALUES (?, ?, ?, ?, ?, ?)";

            if (customizedItems != null && !customizedItems.isEmpty()) {
                // User customized resources via customize_Resource form
                pst = con.prepareStatement(sqlRes);
                for (Object[] row : customizedItems) {
                    String assignId = String.format("ASG-%04d", nextAssignNum++);
                    pst.setString(1, assignId);
                    pst.setString(2, eventId);
                    pst.setString(3, row[0].toString());                          // resource_id
                    pst.setInt(4, Integer.parseInt(row[2].toString()));            // quantity
                    pst.setDouble(5, Double.parseDouble(row[4].toString()));       // total_cost
                    String addedFrom = row[5].toString();
                    if (!"Manual".equals(addedFrom)) {
                        pst.setString(6, addedFrom);                              // package_id
                    } else {
                        pst.setNull(6, java.sql.Types.VARCHAR);
                    }
                    pst.executeUpdate();
                }
            } else {
                // User did NOT customize — insert default package resources
                PreparedStatement fetchPst = con.prepareStatement(
                        "SELECT r.resource_id, pr.quantity, r.cost_per_item "
                        + "FROM package_resources pr "
                        + "JOIN resources r ON pr.resource_id = r.resource_id "
                        + "WHERE pr.package_id = ?");
                fetchPst.setString(1, packageId);
                ResultSet fetchRs = fetchPst.executeQuery();

                pst = con.prepareStatement(sqlRes);
                while (fetchRs.next()) {
                    String assignId = String.format("ASG-%04d", nextAssignNum++);
                    pst.setString(1, assignId);
                    pst.setString(2, eventId);
                    pst.setString(3, fetchRs.getString("resource_id"));
                    int resQty = fetchRs.getInt("quantity");
                    pst.setInt(4, resQty);
                    double unitCost = fetchRs.getDouble("cost_per_item");
                    pst.setDouble(5, resQty * unitCost);
                    pst.setString(6, packageId);
                    pst.executeUpdate();
                }
                fetchRs.close();
                fetchPst.close();
            }

            JOptionPane.showMessageDialog(this,
                    "Booking Saved Successfully!\nEvent ID: " + eventId + "\nBill ID: " + billId,
                    "Success", JOptionPane.INFORMATION_MESSAGE);

            // --- 8. Reset form ---
            resetForm();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error saving booking: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    // Contact number ගෙන් client_id ලබා ගැනීම
    private String getClientId(String contactNo) {
        try {
            String sql = "SELECT client_id FROM clients WHERE contact_number = ?";
            pst = con.prepareStatement(sql);
            pst.setString(1, contactNo);
            rs = pst.executeQuery();
            if (rs.next()) {
                return rs.getString("client_id");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    // Currently logged-in staff_id ලබා ගැනීම (latest staff_log entry)
    private String getLoggedInStaffId() {
        try {
            String sql = "SELECT staff_id FROM staff_log ORDER BY log_id DESC LIMIT 1";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
                return rs.getString("staff_id");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return "S-1000"; // fallback
    }

    // Bill ID generate කිරීම
    private String generateBillId() {
        String newId = "B-0001";
        try {
            String sql = "SELECT MAX(bill_id) AS max_id FROM billing";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next() && rs.getString("max_id") != null) {
                String lastId = rs.getString("max_id");
                int num = Integer.parseInt(lastId.substring(2));
                num++;
                newId = String.format("B-%04d", num);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return newId;
    }

    // Generate unique assignment_id for event_resources (ASG-0001, ASG-0002, ...)
    private String generateAssignmentId() {
        String newId = "ASG-0001";
        try (Connection conn = DBConnect.connect(); PreparedStatement stmt = conn.prepareStatement(
                "SELECT MAX(assignment_id) AS max_id FROM event_resources"); ResultSet result = stmt.executeQuery()) {
            if (result.next() && result.getString("max_id") != null) {
                String lastId = result.getString("max_id");
                int num = Integer.parseInt(lastId.substring(4));
                num++;
                newId = String.format("ASG-%04d", num);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return newId;
    }

    // "08:00 AM" format එකෙන් java.sql.Time ලබා ගැනීම
    private java.sql.Time parseTime(String timeStr) {
        try {
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("hh:mm a");
            java.util.Date parsed = sdf.parse(timeStr);
            return new java.sql.Time(parsed.getTime());
        } catch (Exception e) {
            // fallback - raw HH:mm format try
            try {
                java.text.SimpleDateFormat sdf2 = new java.text.SimpleDateFormat("HH:mm");
                java.util.Date parsed = sdf2.parse(timeStr);
                return new java.sql.Time(parsed.getTime());
            } catch (Exception ex) {
                return java.sql.Time.valueOf("08:00:00");
            }
        }
    }

    // Package list DB ගෙන් load කිරීම
    private void loadPackages() {
        try {
            String sql = "SELECT package_id, package_name FROM package ORDER BY package_id";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            cmbPackage.removeAllItems();
            cmbPackage.addItem(""); // placeholder
            while (rs.next()) {
                cmbPackage.addItem(rs.getString("package_id") + " - " + rs.getString("package_name"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Start time options load කිරීම
    private void loadStartTimes() {
        String[] times = {
            "", "06:00 AM", "07:00 AM", "08:00 AM", "09:00 AM", "10:00 AM",
            "11:00 AM", "12:00 PM", "01:00 PM", "02:00 PM", "03:00 PM",
            "04:00 PM", "05:00 PM", "06:00 PM", "07:00 PM", "08:00 PM",
            "09:00 PM", "10:00 PM"
        };
        txtStartTime.removeAllItems();
        for (String t : times) {
            txtStartTime.addItem(t);
        }
    }

    // Payment status options load කිරීම
    private void loadPaymentStatus() {
        cmbPaymentStatus.removeAllItems();
        cmbPaymentStatus.addItem("Pending");
        cmbPaymentStatus.addItem("Partial");
        cmbPaymentStatus.addItem("Paid");
    }

    // Balance auto-calculate කිරීම
    private void calculateBalance() {
        try {
            double total = txtTotalAmount.getText().trim().isEmpty() ? 0 : Double.parseDouble(txtTotalAmount.getText().trim());
            double advance = txtAdvance.getText().trim().isEmpty() ? 0 : Double.parseDouble(txtAdvance.getText().trim());
            double balance = total - advance;
            txtBalance.setText(String.format("%.2f", balance));
        } catch (NumberFormatException e) {
            txtBalance.setText("");
        }
    }

    // Form reset කිරීම (booking save කළ පසු)
    private void resetForm() {
        NextBid.setText(BookingIdGenarate());
        cmbContact.getEditor().setItem("");
        txtName.setText("");
        cmbPackage.setSelectedIndex(0);
        txtEventDate.setDate(null);
        txtStartTime.setSelectedIndex(0);
        txtVenue.setText("");
        txtGuestCount.setValue(0);
        txtTotalAmount.setText("");
        txtAdvance.setText("");
        txtBalance.setText("");
        cmbPaymentStatus.setSelectedIndex(0);
        customizedItems = null;
    }

    private String BookingIdGenarate() {

        String newId = "E-0001";  // default ID
        try {
            // MAX()
            String sql = "SELECT MAX(event_id) AS max_id FROM events";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            // Data  null 
            if (rs.next() && rs.getString("max_id") != null) {
                String lastId = rs.getString("max_id"); //ex : "S-0001"

                // "S-" (substring(2)
                int num = Integer.parseInt(lastId.substring(2));

                num++; // (1 -> 2)

                //"S-" 
                newId = String.format("E-%04d", num); //  "S-0002"
            }
        } catch (SQLException ex) {
            Logger.getLogger(Admin_Management.class.getName()).log(Level.SEVERE, null, ex);
        }
        return newId;

    }

}
