/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package event_management_system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chamika
 */
public class Package_add extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Package_add.class.getName());

    /**
     * Creates new form Package_add
     */
    PreparedStatement pst;
    ResultSet rs;
    Connection con = DBConnect.connect();
    Admin_Management aM;
    private boolean editMode = false;
    private String selectedPkgId = "";
    private javax.swing.JButton btnUpdate;  // programmatic update button

    public Package_add() {
        initComponents();
        lblNextPackageId.setText(packageIdGenarate());
        
        //UITheme.removeInternalFrameChrome(this);
        customizeUI();
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        
        buildUpdateButton();
        setToAddMode();
    }

    public Package_add(Admin_Management admin) {
        initComponents();
        this.aM = admin;
        lblNextPackageId.setText(packageIdGenarate());
        
        //UITheme.removeInternalFrameChrome(this);
        customizeUI();
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        
        buildUpdateButton();
        setToAddMode();
    }

    /** Creates the Update button  and adds it next to jButton1. */
    private void buildUpdateButton() {
        btnUpdate = new javax.swing.JButton("UPDATE PACKAGE");
        UITheme.styleButton(btnUpdate, UITheme.BTN_BLUE);
        btnUpdate.setPreferredSize(new java.awt.Dimension(156, 41));
        btnUpdate.addActionListener(e -> doUpdate());
        // Add to jPanel5 at the same position as jButton1 but hidden initially
        jPanel5.add(btnUpdate);
        jPanel5.setComponentZOrder(btnUpdate, 0);
        btnUpdate.setBounds(jButton1.getBounds());
    }

    /** Switches to Add mode — shows jButton1, hides btnUpdate. */
    private void setToAddMode() {
        editMode = false;
        selectedPkgId = "";
        setTitle("Add Event Package");
        jButton1.setVisible(true);
        btnUpdate.setVisible(false);
        clearFields();
        lblNextPackageId.setText(packageIdGenarate());
    }

    /**
     * Switches to Update mode: pre-fills all fields with the given package data,
     * shows btnUpdate, hides jButton1 (ADD).
     */
    public void fillForUpdate(String pkgId, String name, String description, String price) {
        editMode = true;
        selectedPkgId = pkgId;
        setTitle("Update Package — " + pkgId);

        lblNextPackageId.setText(pkgId);
        txtPacName.setText(name);
        txtPacDescription.setText(description);
        txtPacPrice.setText(price);

        jButton1.setVisible(false);
        btnUpdate.setVisible(true);
    }

    /** Clears all input fields. */
    private void clearFields() {
        txtPacName.setText("");
        txtPacDescription.setText("");
        txtPacPrice.setText("");
    }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblNextPackageId = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtPacName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPacDescription = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        txtPacPrice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel5.setBackground(UITheme.BG_DEEP);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("EVENT PACKAGE ADD");

        jLabel18.setText("NEXT PACKAGE_ID");

        lblNextPackageId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Package Name");

        txtPacDescription.setColumns(20);
        txtPacDescription.setRows(5);
        jScrollPane2.setViewportView(txtPacDescription);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Description");

        jButton1.setText("ADD PACKAGE");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("Estimate Price");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPacPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPacName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel24)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblNextPackageId, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(lblNextPackageId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPacName, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPacPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 391, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String name = txtPacName.getText().trim();
            String description = txtPacDescription.getText().trim();
//            String vPrice = txtPacPrice.getText().trim();
            String newPackageId = packageIdGenarate();
            int price;

            if (name.isEmpty() || description.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please fill all required fields", "Missing Information", JOptionPane.WARNING_MESSAGE);
                return;
            }

//            try {
//                price = Integer.parseInt(vPrice);
//            } catch (NumberFormatException e) {
//                JOptionPane.showMessageDialog(null, "Price must be a valid number", "Invalid Input", JOptionPane.ERROR_MESSAGE);
//                return;
//            }

            String sql = "INSERT INTO `package` (package_id, package_name, description) VALUES (?, ?, ?)";
            pst = con.prepareStatement(sql);

            pst.setString(1, newPackageId);
            pst.setString(2, name);
            pst.setString(3, description);
//            pst.setInt(4, price);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Package Added Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);

            if (aM != null) {
                aM.refreshPackageTable();
            }
            this.dispose();

        } catch (SQLException ex) {
            // Database error එක console එකේ සහ message box එකක පෙන්නීම
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Database Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Package_add().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNextPackageId;
    private javax.swing.JTextArea txtPacDescription;
    private javax.swing.JTextField txtPacName;
    private javax.swing.JTextField txtPacPrice;
    // End of variables declaration//GEN-END:variables
    
    private void customizeUI() {
        getContentPane().setBackground(UITheme.BG_DEEP);
        
        UITheme.styleTextField(txtPacName);
        UITheme.styleTextField(txtPacPrice);
        UITheme.styleButton(jButton1, UITheme.BTN_BLUE);
        
        txtPacDescription.setBackground(UITheme.BG_CARD);
        txtPacDescription.setForeground(UITheme.FG_WHITE);
        
        javax.swing.JLabel[] labels = {
            jLabel17, jLabel18, jLabel22, jLabel23, jLabel24, lblNextPackageId
        };
        for (javax.swing.JLabel lbl : labels) {
            lbl.setForeground(UITheme.FG_WHITE);
        }
    }

    private String packageIdGenarate() {
        String newId = "P-0001";  // default ID
        try {
            // MAX()
            String sql = "SELECT MAX(package_id) AS max_id FROM package";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            // Data  null 
            if (rs.next() && rs.getString("max_id") != null) {
                String lastId = rs.getString("max_id"); //ex : "S-0001"

                // "S-" (substring(2)
                int num = Integer.parseInt(lastId.substring(2));

                num++; // (1 -> 2)

                //"S-" 
                newId = String.format("P-%04d", num); //  "S-0002"
            }
        } catch (SQLException ex) {
            Logger.getLogger(Admin_Management.class.getName()).log(Level.SEVERE, null, ex);
        }
        return newId;

    }

    /**
     * Runs an UPDATE query for the selected package_id.
     * Called when the btnUpdate button is clicked.
     */
    private void doUpdate() {
        String name        = txtPacName.getText().trim();
        String description = txtPacDescription.getText().trim();
        String vPrice      = txtPacPrice.getText().trim();

        if (name.isEmpty() || description.isEmpty() || vPrice.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please fill in all required fields.",
                    "Missing Information", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int price;
        try {
            price = Integer.parseInt(vPrice);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Price must be a valid whole number.",
                    "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            String sql = "UPDATE `package` SET package_name=?, description=?, price=? WHERE package_id=?";
            pst = con.prepareStatement(sql);
            pst.setString(1, name);
            pst.setString(2, description);
            pst.setInt(3, price);
            pst.setString(4, selectedPkgId);

            int rows = pst.executeUpdate();
            if (rows > 0) {
                JOptionPane.showMessageDialog(this,
                        "Package updated successfully!  (ID: " + selectedPkgId + ")",
                        "Success", JOptionPane.INFORMATION_MESSAGE);
                if (aM != null) {
                    aM.refreshPackageTable();   // refresh table in Admin panel
                }
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this,
                        "Update failed. Package not found.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Admin_Management.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,
                    "Database Error: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}
